### ISSUE TITLE
Alignment doesn't work properly

### ISSUE THREAD

**Issue by Daniel-Kelvich** [GuohongLi/face-alignment-pytorch#1]
I tested your inference with official weights from Adrian Bulat but results aren't quite accurate.
I use pytorch 1.0. And I was forced to replace your fan model with official model, because your model was not able to load some weights from official weights file. Can you please share your pretrained model if you have one. 
![res](https://user-images.githubusercontent.com/19155101/52556852-6454e200-2df6-11e9-92af-8c04828fede6.jpg)
![res2](https://user-images.githubusercontent.com/19155101/52556859-67e86900-2df6-11e9-9779-60e6a2c47470.jpg)

**Comment by GuohongLi** [comment]
@Daniel-Kelvich Since I fixed some problem when tuning the pytorch code according to Adrian Bulat paper, It may be not well work with official weights. Using the training code to get a new model will make it work.

**Comment by GuohongLi** [comment]
@Daniel-Kelvich Pretrained model which I trained using the code will be available at the end of Feb. Something else has taken up my time recently. :)

**Comment by Daniel-Kelvich** [comment]
@GuohongLi Okay, thanks!
